out.println("<html><head><title>Page 2</title></head>");
out.println("<body bgcolor=red>");
HttpSession hs1 = request.getSession(false);
out.println("<h1>Welcome to Page No. 2</h1>");
int visit = Integer.parseInt((String)hs1.getAttribute("visit"))+1;
out.println("<h1>You have visited "+visit+" times</h1>");
hs1.setAttribute("visit", ""+visit);
out.println("<h1>Your Session ID "+hs1.getId()+"</h1>");
out.println("<h1>You Logged in at "+new Date(hs1.getCreationTime()) +"</h1>");
out.println("<h1><a href=Servlet1>Click for Page 1</a></h1>");
out.println("<h1><a href=Servlet3>Click for Page 3</a></h1>");
out.println("<h1><a href=LogoutServlet>Click to Logout</a></h1>");